spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true # 알 수 없는 속성이 있으면 실패(에러) 처리

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/modernworld
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

  jwt:
    access-secret:
      supersecretsecretsecretsecretsecretsupersecretsecretsecretsecretsecretsupersecretsecretsecretsecretsecret
    refresh-secret:
      secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
    access-expiration: 10_800_000 # 3h
    refresh-expiration: 604_800_000 # 7d
    issuer: Eomjunsick.com
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # SQL 쿼리를 표준 출력(console) 에 출력
    properties:
      hibernate:
        format_sql: true # 출력되는 SQL 쿼리를 가독성 좋게 포맷

  devtools:
    restart:
      enabled: false

# 테스트용이라 노출되도 상관 없음.
naver:
  client:
    id: pYRBf_gt4ONiKuhNJiLJ # 테스트용
    secret: 2pIqMHnlsL # 테스트용
    callback-url: https://localhost:8080/naver/auth/callback

kakao:
  client:
    id: f1600533301ee8bb3e83d7039807f2c1 # 테스트용
    secret: xrQU4GHeSLlrvTGn0AAnQ4Zi7fviJyOj # 테스트용
    callback-url: https://localhost:8080/kakao/auth/callback

google:
  client:
    id: 936165156791-45vvvsi9allk1petgtoq6ttrerf7vqh4.apps.googleusercontent.com # 테스트용
    secret: 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 # 테스트용
    callback-url: https://localhost:8080/google/auth/callback

server:
  servlet:
    session:
      timeout: 10m
      cookie:
        name: MODERN_WORLD_V2
        secure: false # 운영환경에서는 true로 설정할것.

logging:
  level:
    root: info
    org.hibernate.SQL: debug # 실행된 SQL 문장
    org.hibernate.type.descriptor.sql.BasicBinder: trace # 쿼리의 PreparedStatement에 바인딩되는 실제 값들을 로그로 출력
    org.springframework.web: debug # 요청 처리 흐름 보기
