name: Sync Labels

on:
  push:
    paths:
      - .github/labels.yaml
  workflow_dispatch:

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: 체크아웃
        uses: actions/checkout@v3

      - name: 깃허브 라벨 동기화
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yaml

### crazy-max/ghaction-github-labeler@v5 공식문서
### https://github.com/crazy-max/ghaction-github-labeler?tab=readme-ov-file#workflow